### ISSUE TITLE
problems

### ISSUE THREAD

**Issue by iiilia** [antter7/task_for_hiring#4]
Добрый день, @antter7 !

не собирается docker-образ
```
Sending build context to Docker daemon  28.18MB
Step 1/8 : FROM jupyter/datascience-notebook
 ---> 9e64f3a158ed
Step 2/8 : USER root
 ---> Using cache
 ---> d869ababdc47
Step 3/8 : RUN mkdir /src
 ---> Using cache
 ---> 33c71bcfecc2
Step 4/8 : RUN mkdir /task-for-hiring-data
 ---> Using cache
 ---> 828b0287723a
Step 5/8 : COPY . /src
 ---> c6d8b84170aa
Step 6/8 : WORKDIR /src
 ---> Running in f67440f46638
Removing intermediate container f67440f46638
 ---> 1517e5742f6f
Step 7/8 : RUN pip install -r requirements.txt
 ---> Running in 3410a2c43f2f
WARNING: The directory '/home/jovyan/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/jovyan/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting alabaster==0.7.12
  Downloading https://files.pythonhosted.org/packages/10/ad/00b090d23a222943eb0eda509720a404f531a439e803f6538f35136cae9e/alabaster-0.7.12-py2.py3-none-any.whl
ERROR: Could not find a version that satisfies the requirement anaconda-client==1.7.2 (from -r requirements.txt (line 2)) (from versions: 1.1.1, 1.2.2)
ERROR: No matching distribution found for anaconda-client==1.7.2 (from -r requirements.txt (line 2))
The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 1
```

как поправите, могли бы заменшить меня в этом issue?

**Comment by antter7** [comment]
теперь точно все, локально у меня все вроде собралось

**Comment by iiilia** [comment]
собралось, действительно
ошибка появилась дальше
```
Traceback (most recent call last):
  File "lib/run.py", line 9, in <module>
    load = pd.read_csv('val.csv')
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 685, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 457, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 895, in init
    self._make_engine(self.engine)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1135, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/conda/lib/python3.7/site-packages/pandas/io/parsers.py", line 1917, in init
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 689, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File b'val.csv' does not exist: b'val.csv'
```

**Comment by antter7** [comment]
путь изменен
